# This is a basic workflow to help you get started with Actions

name: Pack Extensions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  firefox:
    name: Pack Firefox Extension (Manifest V2)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Zip everything
        run: |
          cd 'Shared (Extension)/Resources'
          zip -r -FS ../../purity-firefox.zip * --exclude 'manifest.v3.json'
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Purity-Firefox
          path: purity-firefox.zip
