# This is a basic workflow to help you get started with Actions

name: Pack Extensions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  firefox:
    name: Pack Firefox Extension (Manifest V2)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Change version
        shell: python
        run: |
          import os
          import json
          commit_sha = os.environ['GITHUB_SHA'][:3]
          with open('Shared (Extension)/Resources/manifest.json', 'r') as manifest_file:
              manifest = json.load(manifest_file)
          manifest['version'] = manifest['version'] + '.' + commit_sha
          with open('Shared (Extension)/Resources/manifest.json', 'w') as manifest_file:
              json.dump(manifest, manifest_file)
        
      - name: Zip everything
        run: |
          cd 'Shared (Extension)/Resources'
          zip -r -FS ../../purity-firefox.zip * --exclude 'manifest.v3.json'
        
      - name: Pack into xpi
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: purity-firefox.zip
          channel: unlisted
          apiKey: ${{ secrets.FF_JWT_ISSUER }}
          apiSecret: ${{ secrets.FF_JWT_SECRET }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Purity-Firefox
          path: purity-firefox.xpi
  chromium:
    name: Pack Chromium Extension (Manifest V3 + webextension-polyfill)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Change version
        shell: python
        run: |
          import os
          import json
          commit_sha = os.environ['GITHUB_SHA'][:3]
          with open('Shared (Extension)/Resources/manifest.json', 'r') as manifest_file:
              manifest = json.load(manifest_file)
          manifest['version'] = manifest['version'] + '.' + commit_sha
          with open('Shared (Extension)/Resources/manifest.json', 'w') as manifest_file:
              json.dump(manifest, manifest_file)

      - name: Zip everything
        run: |
          cd 'Shared (Extension)/Resources'
          rm -f manifest.json
          mv manifest.v3.json manifest.json
          zip -r -FS ../../purity-chromium.zip *
      
      - name: Pack into crx
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: purity-chromium.zip
          crxFilePath: purity-chromium.crx
          privateKey: ${{ secrets.CRX_PRIVATE_KEY }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Purity-Chromium
          path: purity-chromium.crx
