# This is a basic workflow to help you get started with Actions

name: Pack and Publish Extensions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  firefox:
    name: Pack and Publish Firefox Extension (Manifest V3)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Zip everything
        run: |
          cd 'Shared (Extension)/Resources'
          zip -r -FS ../../purity-firefox.zip *

      - name: Pack into xpi
        uses: cardinalby/webext-buildtools-firefox-addons-action@v1
        with:
          zipFilePath: purity-firefox.zip
          extensionId: '{CF5ECA06-F807-4AFD-9ACE-0D9FBC602AAF}'
          jwtIssuer: ${{ secrets.FF_JWT_ISSUER }}
          jwtSecret: ${{ secrets.FF_JWT_SECRET }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Purity-Firefox
          path: purity-firefox.zip

  chromium:
    name: Pack and Publish Chromium Extension (Manifest V3 + webextension-polyfill)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Zip everything
        run: |
          cd 'Shared (Extension)/Resources'
          zip -r -FS ../../purity-chromium.zip *

      - name: Get API token
        id: fetchAccessToken
        uses: cardinalby/google-api-fetch-token-action@v1
        with:
          clientId: ${{ secrets.CHROME_CLIENT_ID }}
          clientSecret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refreshToken: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: Upload to Chrome Web Store
        uses: cardinalby/webext-buildtools-chrome-webstore-upload-action@v1
        with:
          zipFilePath: purity-chromium.zip
          extensionId: jmjpplbkcjhbkenmjkefacohljomghef
          apiAccessToken: ${{ steps.fetchAccessToken.outputs.accessToken }}
          waitForUploadCheckCount: 10
          waitForUploadCheckIntervalMs: 180000

      - name: Publish on Google Web Store
        id: webStorePublish
        uses: cardinalby/webext-buildtools-chrome-webstore-publish-action@v1
        with:
          extensionId: jmjpplbkcjhbkenmjkefacohljomghef
          apiAccessToken: ${{ steps.fetchAccessToken.outputs.accessToken }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Purity-Chromium
          path: purity-chromium.zip
