# This is a basic workflow to help you get started with Actions

name: Pack and Publish Extensions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  firefox:
    name: Pack and Publish Firefox Extension (Manifest V2)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Zip everything
        run: |
          cd 'Shared (Extension)/Resources'
          zip -r -FS ../../purity-firefox.zip * --exclude 'manifest.v3.json'
        
      - name: Pack into xpi
        uses: kewisch/action-web-ext@main
        with:
          cmd: sign
          source: purity-firefox.zip
          channel: listed
          apiKey: ${{ secrets.FF_JWT_ISSUER }}
          apiSecret: ${{ secrets.FF_JWT_SECRET }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Purity-Firefox
          path: purity-firefox.xpi
  chromium:
    name: Pack and Publish Chromium Extension (Manifest V3 + webextension-polyfill)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Zip everything
        run: |
          cd 'Shared (Extension)/Resources'
          rm -f manifest.json
          mv manifest.v3.json manifest.json
          zip -r -FS ../../purity-chromium.zip *
      
      - name: Upload to Chrome Web Store
        uses: mnao305/chrome-extension-upload@2.2.0
        with:
          file-path: purity-chromium.zip
          extension-id: jmjpplbkcjhbkenmjkefacohljomghef
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Purity-Chromium
          path: purity-chromium.zip
